title: "Auger's Log"
remote_theme: ziinahzoor/cybersynth-theme
plugins:
  - jekyll-remote-theme

theme_bg: "#1A1A1A"
theme_fg: "#D0D0D0"
theme_accent: "#33FF99"

description: "System logs, cyber wanderings, and data rituals from the Augerist."